#version 460 core

layout(local_size_x = 8, local_size_y = 4, local_size_z = 1) in;

layout(rgba32f, binding = 0) uniform image2D screen;

layout(std430, binding = 0) buffer data
{
    vec4 pix_val[500 * 500];
};

void main()
{
    ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);
    vec4 pixel = pix_val[pixel_coords.y * 500 + pixel_coords.x];
    // vec4 pixel = vec4(1,1,1,1);

    imageStore(screen, pixel_coords, pixel);
}